### ISSUE TITLE
Benchmark discovery fails to import project itself

### ISSUE THREAD

**Issue by TimoRoth** [airspeed-velocity/asv#798] opened 2019-03-28 11:21 UTC
When running my benchmarks, I get:

<details>

```
$ asv run --verbose HEAD~1..HEAD
· Running '/usr/bin/git rev-list --first-parent HEAD~1..HEAD'
  OUTPUT -------->
  defba98bc310505ba5d0c5934f62d0c0fd9980d4
· Creating environments
·· Running '/home/users/timo/Projekte/oggm/.asv/env/dbbfc5d04e8fa83a5fe49b6230dfd79e/bin/python -c pass'
·· Running '/home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/bin/python -c pass'
· Discovering benchmarks
·· Running '/usr/bin/git rev-parse master^{commit}'
   OUTPUT -------->
   defba98bc310505ba5d0c5934f62d0c0fd9980d4
·· Running '/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py discover /home/users/timo/Projekte/oggm/benchmarks /tmp/tmpccwyz93h/result.json' in oggm_conda-py3.6
·· Running '/home/users/timo/Projekte/oggm/.asv/env/dbbfc5d04e8fa83a5fe49b6230dfd79e/bin/python /home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py discover /home/users/timo/Projekte/oggm/benchmarks /tmp/tmpccwyz93h/result.json'
   OUTPUT -------->
   Traceback (most recent call last):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 1301, in <module>
       main()
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 1294, in main
       commands[mode](args)
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 990, in main_discover
       list_benchmarks(benchmark_dir, fp)
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 975, in list_benchmarks
       for benchmark in disc_benchmarks(root):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 873, in disc_benchmarks
       for module in disc_modules(root_name, ignore_import_errors=ignore_import_errors):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 855, in disc_modules
       for item in disc_modules(name, ignore_import_errors=ignore_import_errors):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 843, in disc_modules
       module = import_module(module_name)
     File "/home/users/timo/Projekte/oggm/.asv/env/dbbfc5d04e8fa83a5fe49b6230dfd79e/lib/python3.6/importlib/__init__.py", line 126, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
     File "<frozen importlib._bootstrap>", line 994, in _gcd_import
     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
     File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
     File "/home/users/timo/Projekte/oggm/benchmarks/hef_dynamics.py", line 4, in <module>
       from oggm.tests.funcs import init_hef, get_test_dir
   ModuleNotFoundError: No module named 'oggm'

·· Error running /home/users/timo/Projekte/oggm/.asv/env/dbbfc5d04e8fa83a5fe49b6230dfd79e/bin/python /home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py discover /home/users/timo/Projekte/oggm/benchmarks /tmp/tmpccwyz93h/result.json
·· Failed: trying different commit/environment
·· Running '/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py discover /home/users/timo/Projekte/oggm/benchmarks /tmp/tmpl_w3i6ix/result.json' in oggm_conda-py3.7
·· Running '/home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/bin/python /home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py discover /home/users/timo/Projekte/oggm/benchmarks /tmp/tmpl_w3i6ix/result.json'
   OUTPUT -------->
   Traceback (most recent call last):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 1301, in <module>
       main()
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 1294, in main
       commands[mode](args)
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 990, in main_discover
       list_benchmarks(benchmark_dir, fp)
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 975, in list_benchmarks
       for benchmark in disc_benchmarks(root):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 873, in disc_benchmarks
       for module in disc_modules(root_name, ignore_import_errors=ignore_import_errors):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 855, in disc_modules
       for item in disc_modules(name, ignore_import_errors=ignore_import_errors):
     File "/home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py", line 843, in disc_modules
       module = import_module(module_name)
     File "/home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/lib/python3.7/importlib/__init__.py", line 127, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
     File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
     File "<frozen importlib._bootstrap>", line 983, in _find_and_load
     File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
     File "<frozen importlib._bootstrap_external>", line 728, in exec_module
     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
     File "/home/users/timo/Projekte/oggm/benchmarks/hef_dynamics.py", line 4, in <module>
       from oggm.tests.funcs import init_hef, get_test_dir
   ModuleNotFoundError: No module named 'oggm'

·· Error running /home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/bin/python /home/users/timo/miniconda3/envs/asv_env/lib/python3.7/site-packages/asv/benchmark.py discover /home/users/timo/Projekte/oggm/benchmarks /tmp/tmpl_w3i6ix/result.json
·· Failed to build the project and import the benchmark suite.
```

</details>

However, when I manually run .asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/bin/python I can "import oggm" and "from oggm.tests.funcs import init_hef, get_test_dir" just fine. I'm a bit at a loss what's going on there.
This happens regardless whether I'm using pip or conda to create the environment.
Happens with both latest release and current master as well.
Deleting .asv only results in the exact same results again after recreating the environments.

**Comment by TimoRoth** [comment] 2019-03-28 13:28
Looking some more into this, it actually did not install the project itself, the import only works because I happened to be in the right dir when trying it.

The install looks like this:
```
·· Running '/home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/bin/python -mpip install /home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/asv-build-cache/defba98bc310505ba5d0c5934f62d0c0fd9980d4/oggm-1.1+12.gdefba98-py3-none-any.whl'
   OUTPUT -------->
   Requirement already satisfied: oggm==1.1+12.gdefba98 from file:///home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/asv-build-cache/defba98bc310505ba5d0c5934f62d0c0fd9980d4/oggm-1.1%2B12.gdefba98-py3-none-any.whl in /home/users/timo/Projekte/oggm/.asv/env/c503f31ae082fa0e9e3e2dc8f4aa8716/project (1.1+12.gdefba98)
```

So pip for some reason thinks oggm is already installed, even though it clearly is not.
When I run that exact command manually, it proceeds to install oggm just fine and runs the benchmarks successfully if I run asv afterwards.

**Comment by TimoRoth** [comment] 2019-03-28 13:42
I have worked around this for now by doing
`"install_command": ["python -mpip install --upgrade {wheel_file}"]`

Which results in:
```
   Installing collected packages: oggm
     Found existing installation: oggm 1.1+12.gdefba98
       Can't uninstall 'oggm'. No files were found to uninstall.
   Successfully installed oggm-1.1+12.gdefba98
```

Really not sure why it thinks oggm was already installed in that env, even though it clearly was not. Almost seems like parts of the python path/python home of the outside env are spilling into the test env, even though oggm isn't installed there either.

**Comment by pv** [comment] 2019-03-28 13:58
Does oggm have a custom asv plugin?

**Comment by TimoRoth** [comment] 2019-03-28 14:03
It does, because we have quite complex dependencies that cannot be installed in any other sane way.

**Comment by pv** [comment] 2019-05-12 21:12
Duplicate of #805 I think (if not, please comment).

**Closed by pv** 2019-05-12 21:12 UTC
