### ISSUE TITLE
Misleading overview plots

### ISSUE THREAD

**Issue by QuLogic** [airspeed-velocity/asv#916] opened 2020-04-29 03:53 UTC
A long time ago, I ran some benchmarks on Matplotlib, but we never got them running full time. I'm starting to run those again, but there's a really big break in testing. [Results are posted here](https://matplotlib.org/mpl-bench/).

In the overview page, there is for example, this plot:
![image](https://user-images.githubusercontent.com/302469/80559116-8fe7cc00-89aa-11ea-8de3-9a532224a01e.png)
but the actual plot looks like:
![image](https://user-images.githubusercontent.com/302469/80559350-3fbd3980-89ab-11ea-801d-a791ec776c40.png)

The overview seems to say that there was a huge regression in runtime, but in actuality, it's _much faster_.

**Comment by pv** [comment] 2020-05-14 20:56
Duplicate of gh-894? If so, fixed in master branch.

**Closed** 2020-05-14 21:03 UTC
Labels: duplicate
