### ISSUE TITLE
Doesn't work with homebrew ccache

### ISSUE THREAD

**Issue by mdboom** [airspeed-velocity/asv#196] opened 2015-01-21 13:46 UTC
As reported in https://github.com/spacetelescope/asv/issues/194#issue-54718191 there may be an issue with homebrew's ccache.

Cc: @qwhelan

**Comment by pv** [comment] 2019-06-01 12:52
Many changes since in this respect, and status of the issue is unclear, so closing.

**Closed by pv** 2019-06-01 12:52 UTC
Labels: bug, needs-info
