### ISSUE TITLE
ImportError: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by officialasishkumar** [airspeed-velocity/asv#1419] opened 2024-07-16 11:48 UTC
While running `asv run master^! -j | tee asv-output.txt` on https://github.com/tardis-sn/tardis, I am getting an error: 

```
asv run master^! --skip-existing-successful -j | tee asv-output.txt
Traceback (most recent call last):
  File "/home/charon/anaconda3/envs/tardis/bin/asv", line 5, in <module>
    from asv.__main__ import main
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/site-packages/asv/__init__.py", line 4, in <module>
    from asv import plugin_manager  # noqa F401 Needed to load the plugins
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/site-packages/asv/plugin_manager.py", line 76, in <module>
    plugin_manager.load_plugins(plugins)
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/site-packages/asv/plugin_manager.py", line 29, in load_plugins
    mod = importlib.import_module(name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/site-packages/asv/plugins/_mamba_helpers.py", line 9, in <module>
    import libmambapy
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/charon/anaconda3/envs/tardis/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libarchive.so.19: cannot open shared object file: No such file or directory
```

**Comment by HaoZeke** [comment] 2024-08-12 09:10
Could you provide the versions for `libmambapy` and `conda-build`? The `mamba` plugin's dependencies can be finicky.

I can't reproduce this on `main@484fbcd` otherwise (though `-j` is not valid for `mamba`, needs upstream support).

```
asv --version                        
asv 0.6.3.dev29+g484fbcd
git clone git@github.com:tardis-sn/tardis --single-branch
asv run master^! | tee asv-output.txt
· Creating environments
Transaction starting
...
To activate this environment, use:

    mamba activate /home/rgoswami/Git/Github/Quansight/asvWork/bugReports/tardis/.asv/env/a608f06e1e386bf8e9bd3bd2e346b88a

Or to execute a single command in this environment, use:

    mamba run -p /home/rgoswami/Git/Github/Quansight/asvWork/bugReports/tardis/.asv/env/a608f06e1e386bf8e9bd3bd2e346b88a mycommand
· Discovering benchmarks
·· Uninstalling from mamba-py3.9
·· Building 30427ff0 <master> for mamba-py3.9
·· Installing 30427ff0 <master> into mamba-py3.9
· Running 23 total benchmarks (1 commits * 1 environments * 23 benchmarks)
[ 0.00%] · For tardis commit 30427ff0 <master>:
[ 0.00%] ·· Benchmarking mamba-py3.9
[ 2.17%] ··· Running (opacities_opacity.BenchmarkMontecarloMontecarloNumbaOpacities.time_compton_opacity_calculation--).......................
[52.17%] ··· ...baOpacities.time_compton_opacity_calculation          433±200ns
[54.35%] ··· ...ities.time_pair_creation_opacity_calculation          415±200ns
[56.52%] ··· ...ies.time_photoabsorption_opacity_calculation          405±200ns
...
```

**Comment by HaoZeke** [comment] 2024-08-26 00:46
Closing for now as unreproducible / tool version errors.

**Closed by HaoZeke** 2024-08-26 00:46 UTC
Labels: env:mamba
