### ISSUE TITLE
asv fails to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by bwohlberg** [airspeed-velocity/asv#576] opened 2017-11-10 00:05 UTC
Using python2.7 and virtualenv from the ubuntu packages, and `asv` installed via pip, ``asv run`` fails while creating the environment:

> $ asv run
· Creating environments.
·· Failure creating environment for virtualenv-py2.7Traceback (most recent call last):
  File "/usr/local/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/usr/local/lib/python2.7/dist-packages/asv/commands/run.py", line 123, in run_from_conf_args
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/asv/commands/run.py", line 168, in run
    Setup.perform_setup(environments, parallel=parallel)
  File "/usr/local/lib/python2.7/dist-packages/asv/commands/setup.py", line 78, in perform_setup
    list(map(_create, environments))
  File "/usr/local/lib/python2.7/dist-packages/asv/commands/setup.py", line 20, in _create
    env.create()
  File "/usr/local/lib/python2.7/dist-packages/asv/environment.py", line 455, in create
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/asv/plugins/virtualenv.py", line 147, in _setup
    self._install_requirements()
  File "/usr/local/lib/python2.7/dist-packages/asv/plugins/virtualenv.py", line 162, in _install_requirements
    self.run_executable('pip', pip_args)
  File "/usr/local/lib/python2.7/dist-packages/asv/environment.py", line 556, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/asv/util.py", line 361, in check_output
    proc = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

The relevant parts of `asv.conf.json` are:

>    "repo": ".",
    "environment_type": "virtualenv",
     "pythons": ["2.7"],

Is this a configuration error, or a bug?

**Comment by bwohlberg** [comment] 2017-11-10 13:56
The development code in the repo doesn't give this error, so I assume it's a bug in the version available via `pip`.

**Comment by pv** [comment] 2017-11-10 20:48
There may be something strange in your Python setup that makes virtualenv not produce virtualenvs with executable pip scripts.

**Comment by bwohlberg** [comment] 2017-11-10 20:58
Possibly, but I tried it on two different machines with the same result, so I doubt it's just some localized configuration problem.

**Comment by pv** [comment] 2017-11-10 21:01
Cannot reproduce here.

**Comment by bwohlberg** [comment] 2017-11-10 21:05
OK, I'll see if I can do that. Any suggestions for a simple way of testing your broken virtualenv hypothesis?

**Comment by pv** [comment] 2017-11-10 21:10
Try if `python -mvirtualenv` produces a virtualenv with an executable `pip`, under the directory configured as the env directory in asv.conf

**Comment by bwohlberg** [comment] 2017-11-10 22:57
The virtualenv and its included `pip` are superficially fine, but it appears the `pip` can't be executed because the shebang line length exceeds the OS maximum, as indicated by the error `bash: bin/pip: <path>: bad interpreter: No such file or directory`, where `<path>` is a truncated version of the actual path in the shebang line. The path is too long because virtualenv is inserting an absolute path to a directory within a deep directory tree.

**Comment by pv** [comment] 2017-11-10 23:04
ok, it was then addressed in gh-569.

**Closed by pv** 2017-11-10 23:04 UTC
